const carData = {
"Alfa Romeo": ["Giulietta", "Stelvio", "Tonale", "Giulia"].sort(),
"Audi": ["A1", "A3", "A4", "A5", "A6", "A7", "A8", "E-Tron", "Q2", "Q3", "Q4 E-Tron", "Q5", "Q7", "Q8", "RS", "TT"].sort(),
"BMW": ["1 Serisi", "2 Serisi", "3 Serisi", "4 Serisi", "5 Serisi", "6 Serisi", "7 Serisi", "8 Serisi", "iX", "iX3", "i4", "i7", "M Serisi", "X1", "X2", "X3", "X4", "X5", "X6", "X7", "Z4"].sort(),
"Chery": ["Omoda 5", "Tiggo 7 Pro", "Tiggo 8 Pro"].sort(),
"Citroen": ["Ami", "Berlingo", "C-Elysee", "C3", "C3 Aircross", "C4", "C4 X", "C5 Aircross"].sort(),
"Dacia": ["Duster", "Jogger", "Sandero", "Spring"].sort(),
"DS Automobiles": ["DS 3", "DS 4", "DS 7", "DS 9"].sort(),
"Fiat": ["500", "Doblo", "Egea", "Fiorino", "Panda", "Punto", "Scudo", "Ulysse"].sort(),
"Ford": ["B-Max", "C-Max", "Focus", "Fiesta", "Galaxy", "Kuga", "Mondeo", "Mustang", "Puma", "Ranger", "S-Max", "Tourneo Connect", "Tourneo Courier", "Tourneo Custom", "Transit"].sort(),
"Honda": ["Accord", "City", "Civic", "CR-V", "HR-V", "Jazz"].sort(),
"Hyundai": ["Accent", "Bayon", "Elantra", "Getz", "i10", "i20", "i30", "Ioniq", "Kona", "Santa Fe", "Staria", "Tucson"].sort(),
"Jeep": ["Avenger", "Compass", "Grand Cherokee", "Renegade", "Wrangler"].sort(),
"Kia": ["Ceed", "Cerato", "EV6", "Niro", "Picanto", "Rio", "Sorento", "Sportage", "Stonic", "XCeed"].sort(),
"Land Rover": ["Defender", "Discovery", "Range Rover", "Range Rover Evoque", "Range Rover Sport", "Range Rover Velar"].sort(),
"Mercedes-Benz": ["A Serisi", "B Serisi", "C Serisi", "CLA", "CLS", "E Serisi", "EQA", "EQB", "EQC", "EQE", "EQS", "G Serisi", "GLA", "GLB", "GLC", "GLE", "GLS", "S Serisi", "Vito"].sort(),
"MG": ["E-HS", "HS", "ZS"].sort(),
"Mini": ["Cooper", "Clubman", "Countryman"].sort(),
"Nissan": ["Juke", "Micra", "Navara", "Qashqai", "X-Trail"].sort(),
"Opel": ["Astra", "Combo", "Corsa", "Crossland", "Grandland", "Insignia", "Mokka", "Zafira"].sort(),
"Peugeot": ["2008", "208", "3008", "301", "308", "408", "5008", "508", "Partner", "Rifter"].sort(),
"Porsche": ["718", "911", "Cayenne", "Macan", "Panamera", "Taycan"].sort(),
"Renault": ["Austral", "Captur", "Clio", "Express", "Fluence", "Kadjar", "Kangoo", "Koleos", "Megane", "Symbol", "Taliant", "Zoe"].sort(),
"Seat": ["Arona", "Ateca", "Ibiza", "Leon", "Tarraco"].sort(),
"Skoda": ["Fabia", "Kamiq", "Karoq", "Kodiaq", "Octavia", "Scala", "Superb"].sort(),
"Suzuki": ["Jimny", "S-Cross", "Swift", "Vitara"].sort(),
"Togg": ["T10X"].sort(),
"Toyota": ["C-HR", "Camry", "Corolla", "Corolla Cross", "Hilux", "Land Cruiser", "Proace", "RAV4", "Yaris", "Yaris Cross"].sort(),
"Volkswagen": ["Amarok", "Arteon", "Caddy", "Caravelle", "Golf", "Jetta", "Passat", "Polo", "T-Cross", "T-Roc", "Taigo", "Tiguan", "Touareg", "Transporter"].sort(),
"Volvo": ["S60", "S90", "V60", "V90", "XC40", "XC60", "XC90"].sort(),
};
export default carData; 